version: '3.6'

services:    
  packetbeat:
    container_name: packetbeat
    build:
      context: packetbeat/
      args:
        ELK_VERSION: $ELK_VERSION
    command: packetbeat setup -e
    user: root
    cap_add: ['NET_RAW', 'NET_ADMIN'] # Grant some elevated privileges to capture network traffic.
    network_mode: host # Allow to capture traffic from host.
    volumes:
      - type: bind
        source: ./packetbeat/config/packetbeat.yml
        target: /usr/share/packetbeat/packetbeat.yml
        read_only: true
        
  metricbeat:
    container_name: metricbeat
    build:
      context: metricbeat/
      args:
        ELK_VERSION: $ELK_VERSION
    command: bash -c "metricbeat -e -strict.perms=false && metricbeat modules enable elasticsearch && metricbeat setup"
    user: root
    network_mode: host
    volumes:
      - type: bind
        source: ./metricbeat/config/metricbeat.yml
        target: /usr/share/metricbeat/metricbeat.yml
        read_only: true
  auditbeat:
    container_name: auditbeat
    build:
      context: auditbeat/
      args:
        ELK_VERSION: $ELK_VERSION
    command: auditbeat setup
    user: root
    network_mode: host
    volumes:
      - type: bind
        source: ./auditbeat/config/auditbeat.yml
        target: /usr/share/auditbeat/auditbeat.yml
        read_only: true
